### ISSUE TITLE
Usage of Lists vs Tables

### ISSUE THREAD

**Issue by ThunderSon** [Link-/Arab_OSC#3]
I noticed that the data was set as a list instead of a table.
Why was the change done? Lists are easier to follow through, tables get complex pretty fast :)
_Adding things to a list are easier as well than adding them to a MD table_

**Comment by Link-** [comment]
100%. Lists are much easier to maintain but less aesthetically appealing and harder to read. I also want to add the starts of the repos and potentially other columns down the line (like a brief description of the project etc.). I feel these look much cleaner in a table

**Comment by Link-** [comment]
Closing this as it's stale for 12 days now
